version: "3.9"

services:
  app-node:
    container_name: app-node
    restart: unless-stopped
    env_file:
      - .env
    build: 
      context: ./my_app
      target: dev
    ports:
      - 8080:$PORT
    volumes:
      - ./my_app:/app
      # - ./my_app/node_modules:/app/node_modules
      - app:/app/node_modules
    environment:
      - DB_HOST=mongodb
      - NODE_ENV=dev
    networks:
      - example-net
      
  mongodb:
    container_name: mongodb
    image: mongo:6.0.4
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 7017:$DB_PORT
    volumes:
      - ./db:/data/db
    networks:
      - example-net
    command: mongod --quiet --logpath /dev/null

networks:
  example-net:
    driver: bridge
volumes:
  app:
  # db: